version: '3.8'

services:

  wordpress-database:
    image: mysql:5.7
    ports: 
      - 3306:3306
    volumes:
      - wordpress-database_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - wordpress-database
    image: phpmyadmin/phpmyadmin
    ports:
      - 7778:80
    restart: always
    environment:
      - PMA_HOST=wordpress-database
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - wpsite
      
  wordpress:
    depends_on:
      - wordpress-database
    image: wordpress:latest
    ports: 
      - 7777:80
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      - WORDPRESS_DB_HOST=wordpress-database:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  wordpress-database_data:
  